version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment: 
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=simple_blog_api

  api:
    depends_on: 
      - postgres
    image: sengarnab/simple_blog_api_ts-master_api
    build: 
      dockerfile: Dockerfile.dev
      context: .
    ports: 
      - "3000:3000"
    volumes: 
      - /usr/app/node_modules
      - .:/usr/app
    environment: 
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=simple_blog_api